# Generated by Django 4.2.3 on 2023-07-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnownImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognize.profile')),
            ],
        ),
    ]
